baseURL = 'http://sesion04.norwayeast.cloudapp.azure.com/'
relativeURLs = true
canonifyURLs = false
languageCode = 'en-us'
title = 'juanMecanico'
theme = 'ananke'
[[menu.main]]
    name = "Miembros"
    url = "/Miembros/"
    weight = 1

[[menu.main]]
    name = "Contacto"
    url = "/contacto/"
    weight = 2

    [markup.goldmark.renderer]
    unsafe = true

    